version: '3'
services:

  deekor_nginx:
    image: nginx:latest
    container_name: deekor_nginx
    ports:
      - "9876:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-logs:/var/log/nginx
    links:
      - deekor_db
      - deekor_php
    networks:
      - app-network

  deekor_php:
    container_name: deekor_php
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
    links:
      - deekor_db
    networks:
      - app-network

  deekor_db:
    container_name: deekor_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app-network

  deekor_frontend:
    container_name: deekor_frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /frontend/node_modules
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge